DROP DATABASE IF EXISTS `enrolledstudents`;
CREATE DATABASE IF NOT EXISTS `enrolledstudents`;
USE `enrolledstudents`;


DROP TABLE IF EXISTS `college`;
CREATE TABLE IF NOT EXISTS `college` (
	`CollegeName` varchar(255) NOT NULL,
	`CollegeCode` varchar(20) NOT NULL,
	PRIMARY KEY (`CollegeCode`),
	UNIQUE KEY unique_college_name (CollegeName),
	UNIQUE KEY unique_college_code (CollegeCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO college(CollegeName, CollegeCode) VALUES
	('College of Arts and Social Sciences', 'CASS'),
	('College of Economics, Business, and Accountancy', 'CEBA'),
	('College of Science and Mathematics', 'CSM'),
	('College of Computer Studies', 'CCS'),
	('College of Engineering and Technology', 'CET'),
	('College of Nursing', 'CON'),
	('College of Education', 'CED');


DROP TABLE IF EXISTS `course`;
CREATE TABLE IF NOT EXISTS `course` (
  `CourseName` varchar(255) NOT NULL,
  `CourseCode` varchar(20) NOT NULL,
	`CollegeCode` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CourseCode`),
	UNIQUE KEY unique_course_code (CourseCode),
  CONSTRAINT `fk_course_college` FOREIGN KEY (`CollegeCode`) REFERENCES `college` (`CollegeCode`) 
	ON UPDATE CASCADE
	ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO course(CourseName, CourseCode, CollegeCode) VALUES
	('Bachelor of Arts in English Language Studies', 'BAELS', 'CASS'),
	('Bachelor of Arts in Filipino', 'BAF', 'CASS'),
	('Bachelor of Arts in History', 'BAH', 'CASS'),
	('Bachelor of Arts in Panitikan', 'BAP', 'CASS'),
	('Bachelor of Arts in Political Science', 'BAPolSci', 'CASS'),
	('Bachelor of Arts in Psychology', 'BAPsych', 'CASS'),
	('Bachelor of Arts in Sociology', 'BASoc', 'CASS'),
	('Bachelor of Science in Psychology', 'BSPsych', 'CASS'),
	('Bachelor of Science in Philosophy', 'BSPhil', 'CASS'),
	('Bachelor of Science in Accountancy', 'BSA', 'CEBA'),
	('Bachelor of Science in Economics', 'BSEcon', 'CEBA'),
	('Bachelor of Science in Entrepreneurship', 'BSEntrep', 'CEBA'),
	('Bachelor of Science in Hospitality Management', 'BSHM', 'CEBA'),
	('Bachelor of Science in Business Administration', 'BSBA', 'CEBA'),
	('Bachelor of Science in Animal Biology', 'BSBioANB', 'CSM'),
	('Bachelor of Science in Plant Biology', 'BSBioPB', 'CSM'),
	('Bachelor of Science in Biodiversity', 'BSBiodiv', 'CSM'),
	('Bachelor of Science in Chemistry', 'BSChem', 'CSM'),
	('Bachelor of Science in Marine Biology', 'BSMarBio', 'CSM'),
	('Bachelor of Science in Mathematics', 'BSMath', 'CSM'),
	('Bachelor of Science in Physics', 'BSPhys', 'CSM'),
	('Bachelor of Science in Statistics', 'BSStat', 'CSM'),
	('Bachelor of Science in Computer Application', 'BSCA', 'CCS'),
	('Bachelor of Science in Computer Science', 'BSCS', 'CCS'),
	('Bachelor of Science in Information Systems', 'BSIS', 'CCS'),
	('Bachelor of Science in Information Technology', 'BSIT', 'CCS'),
	('Bachelor of Science in Nursing', 'BSN', 'CON'),
	('Bachelor of Science in Ceramics Engineering', 'BSCerE', 'CET'),
	('Bachelor of Science in Checmical Engineering', 'BSChE', 'CET'),
	('Bachelor of Science in Civil Engineering', 'BSCE', 'CET'),
	('Bachelor of Science in Computer Engineering', 'BSComEng', 'CET'),
	('Bachelor of Science in Electrical Engineering', 'BSEE', 'CET'),
	('Bachelor of Science in Electronics Engineering', 'BSECE', 'CET'),
	('Bachelor of Science in Environment Engineering', 'BSEnvEng', 'CET'),
	('Bachelor of Science in Industrial Automation and Mechanism', 'BSIAM', 'CET'),
	('Bachelor of Science in Mechanical Engineering', 'BSME', 'CET'),
	('Bachelor of Science in Metallurgical Engineering', 'BSMetE', 'CET'),
	('Bachelor of Science in Mining Engineering', 'BSEM', 'CET'),
	('Bachelor of Elementary Education', 'BEEd', 'CED'),
	('Bachelor of Secondary Education', 'BSEd', 'CED'),
	('Bachelor of Technical-Vocation Teacher Education', 'BTVTEd', 'CED'),
	('Bachelor of Technology and Livelihood Education', 'BTLEd', 'CED'),
	('Bachelor of Physical Education', 'BPEd', 'CED');


DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student (
  FirstName varchar(199) NOT NULL,
  LastName varchar(199) NOT NULL,
  ID char(9) NOT NULL,
  YearLevel char(1) NOT NULL,
  Gender varchar(10) NOT NULL,
  CourseCode varchar(20) DEFAULT NULL,
	profile_url TEXT DEFAULT NULL,
  UNIQUE KEY unique_name (FirstName, LastName),
  UNIQUE KEY unique_id (ID),
  CONSTRAINT fk_student_course FOREIGN KEY (CourseCode) REFERENCES course (CourseCode)
	ON UPDATE CASCADE
	ON DELETE SET NULL
);


INSERT INTO student(FirstName, LastName, ID, YearLevel, Gender, CourseCode) VALUES
	('Michael Christopher', 'Rodriguez', '2023-6466', '5', 'Non-Binary', 'BSCS'),
	('Isabella Grace', 'Smith', '2022-7358', '4', 'Female', 'BSN'),
	('John Joseph', 'Johnson', '2024-3508', '2', 'Female', 'BSBioANB'),
	('William Christopher', 'Garcia', '2020-3442', '3', 'Non-Binary', 'BSBioPB'),
	('Alexander Amelia', 'Martinez', '2022-0789', '3', 'Female', 'BSCerE'),
	('Emma Elizabeth', 'Jones', '2024-1465', '3', 'Male', 'BSEcon'),
	('Emma Charlotte', 'Martinez', '2023-4337', '3', 'Female', 'BSEcon'),
	('John Christopher', 'Martinez', '2022-8975', '4', 'Female', 'BAH'),
	('Ava Daniel', 'Smith', '2021-4020', '1', 'Male', 'BSIAM'),
	('William Christopher', 'Smith', '2023-4234', '2', 'Non-Binary', 'BSEcon'),
	('Ava David', 'Smith', '2023-8389', '3', 'Non-Binary', 'BAH'),
	('William David', 'Garcia', '2024-4606', '4', 'Male', 'BSCS'),
	('Alexander Matthew', 'Rodriguez', '2023-4564', '3', 'Non-Binary', 'BSPhys'),
	('Alexander Amelia', 'Brown', '2023-4544', '3', 'Male', 'BSIS'),
	('Isabella Elizabeth', 'Garcia', '2021-1859', '3', 'Female', 'BSIT'),
	('John David', 'Jones', '2023-1755', '3', 'Female', 'BSBA'),
	('Isabella David', 'Miller', '2021-8295', '1', 'Female', 'BSPhys'),
	('Ava Amelia', 'Davis', '2020-4358', '1', 'Female', 'BSChE'),
	('John Joseph', 'Jones', '2020-5350', '5', 'Non-Binary', 'BSEntrep'),
	('Michael Joseph', 'Jones', '2023-0274', '1', 'Non-Binary', 'BAH'),
	('Emma Matthew', 'Smith', '2020-2837', '3', 'Non-Binary', 'BAP'),
	('Ava Charlotte', 'Rodriguez', '2024-4900', '4', 'Male', 'BAF'),
	('William Christopher', 'Brown', '2020-8964', '2', 'Female', 'BSME'),
	('Ava David', 'Johnson', '2023-2375', '5', 'Male', 'BSHM'),
	('James Matthew', 'Smith', '2022-6015', '2', 'Non-Binary', 'BSPhil'),
	('Sophia David', 'Garcia', '2022-7072', '5', 'Female', 'BSCA'),
	('Emma Grace', 'Smith', '2021-7085', '5', 'Female', 'BTVTEd'),
	('Emma Joseph', 'Davis', '2021-0111', '1', 'Male', 'BTVTEd'),
	('Michael David', 'Rodriguez', '2021-4334', '5', 'Male', 'BSHM'),
	('Olivia Elizabeth', 'Garcia', '2022-8101', '4', 'Male', 'BSCA'),
	('Isabella Elizabeth', 'Martinez', '2024-4930', '5', 'Male', 'BSChem'),
	('Alexander Christopher', 'Brown', '2023-1640', '2', 'Male', 'BPEd'),
	('Olivia Mia', 'Brown', '2024-3356', '4', 'Non-Binary', 'BAELS'),
	('John Joseph', 'Miller', '2020-6416', '5', 'Non-Binary', 'BSIT'),
	('Michael Elizabeth', 'Davis', '2024-9916', '2', 'Non-Binary', 'BSEntrep'),
	('Ava David', 'Conquer', '2022-4047', '5', 'Female', 'BSCerE'),
	('Michael Grace', 'Brown', '2022-5257', '3', 'Non-Binary', 'BSEd'),
	('Ava Joseph', 'Garcia', '2021-4467', '3', 'Non-Binary', 'BAP'),
	('Michael David', 'Squirell', '2024-2078', '2', 'Female', 'BSEnvEng'),
	('Michael Christopher', 'Garcia', '2020-7977', '1', 'Male', 'BSEd'),
	('Olivia Elizabeth', 'Martinez', '2022-3477', '4', 'Male', 'BSECE'),
	('John Amelia', 'Williams', '2020-2689', '4', 'Male', 'BAELS'),
	('Isabella Christopher', 'Rodriguez', '2021-0369', '3', 'Male', 'BEEd'),
	('Sophia Amelia', 'Garcia', '2022-2806', '4', 'Male', 'BAPolSci'),
	('Emma Christopher', 'Jones', '2023-8554', '1', 'Male', 'BTLEd'),
	('Emma Charlotte', 'Brown', '2023-0281', '2', 'Female', 'BSCerE'),
	('Michael David', 'Davis', '2020-4152', '2', 'Female', 'BAPolSci'),
	('William Joseph', 'Johnson', '2024-9275', '2', 'Male', 'BSCerE'),
	('James Elizabeth', 'Brown', '2024-0036', '4', 'Male', 'BASoc'),
	('Michael Joseph', 'Davis', '2021-1287', '2', 'Female', 'BAPolSci'),
	('Isabella Charlotte', 'Miller', '2024-7495', '3', 'Female', 'BSCE'),
	('Ava Christopher', 'Jones', '2020-5956', '4', 'Non-Binary', 'BSN'),
	('Isabella Christopher', 'Smith', '2020-8070', '4', 'Non-Binary', 'BAELS'),
	('Sophia David', 'Williams', '2020-4650', '1', 'Non-Binary', 'BSBioPB'),
	('Sophia Grace', 'Williams', '2021-7235', '4', 'Male', 'BSEd'),
	('Alexander Daniel', 'Jones', '2021-9054', '4', 'Non-Binary', 'BAH'),
	('Sophia Charlotte', 'Miller', '2022-2409', '3', 'Female', 'BSN'),
	('Isabella Christopher', 'Martinez', '2022-5722', '4', 'Non-Binary', 'BSME'),
	('James Matthew', 'Williams', '2024-8102', '5', 'Female', 'BSIS'),
	('William Grace', 'Miller', '2024-0030', '4', 'Non-Binary', 'BTLEd'),
	('Ava David', 'Smithereens', '2021-2703', '3', 'Female', 'BSMetE'),
	('Alexander Grace', 'Martinez', '2023-0088', '1', 'Female', 'BSIS'),
	('Olivia Elizabeth', 'Rodriguez', '2022-8425', '1', 'Male', 'BSBA'),
	('Isabella Matthew', 'Davis', '2020-8439', '4', 'Male', 'BSEE'),
	('James Christopher', 'Brown', '2021-2392', '4', 'Non-Binary', 'BSCA'),
	('William Elizabeth', 'Smith', '2023-5096', '1', 'Female', 'BSECE'),
	('Isabella Joseph', 'Rodriguez', '2020-8358', '5', 'Non-Binary', 'BSEE'),
	('John Christopher', 'Rodriguez', '2024-1104', '4', 'Male', 'BSEE'),
	('Sophia David', 'Brown', '2021-9811', '2', 'Non-Binary', 'BAELS'),
	('Alexander Amelia', 'Rainbow', '2021-4213', '1', 'Female', 'BSCE'),
	('Emma Grace', 'Davis', '2023-9183', '1', 'Male', 'BAPolSci'),
	('Sophia Grace', 'Jones', '2023-9328', '1', 'Non-Binary', 'BSIT'),
	('Olivia Joseph', 'Smith', '2021-5876', '5', 'Non-Binary', 'BTLEd'),
	('Isabella David', 'Johnson', '2020-5631', '5', 'Female', 'BPEd'),
	('Sophia Matthew', 'Rodriguez', '2024-0285', '5', 'Non-Binary', 'BSME'),
	('James Grace', 'Jones', '2022-1524', '3', 'Female', 'BTVTEd'),
	('William Charlotte', 'Johnson', '2022-9540', '3', 'Non-Binary', 'BSA'),
	('William David', 'Hope', '2023-1531', '2', 'Female', 'BSCE'),
	('William Joseph', 'Williams', '2022-3211', '2', 'Non-Binary', 'BSEd'),
	('Olivia Grace', 'Martinez', '2022-0308', '1', 'Female', 'BSCA'),
	('Sophia Joseph', 'Davis', '2022-5267', '2', 'Female', 'BAP'),
	('John Mia', 'Brown', '2020-1286', '4', 'Female', 'BSBA'),
	('John Matthew', 'Smith', '2022-8475', '2', 'Female', 'BAELS'),
	('Alexander Christopher', 'Rodriguez', '2021-6988', '2', 'Female', 'BSME'),
	('Isabella Charlotte', 'Brown', '2020-5506', '1', 'Non-Binary', 'BSEd'),
	('Michael Christopher', 'Jones', '2024-1226', '3', 'Male', 'BSA'),
	('Sophia Matthew', 'Martinez', '2020-6210', '5', 'Female', 'BSIAM'),
	('William Charlotte', 'Jones', '2020-4411', '4', 'Male', 'BPEd'),
	('Olivia Matthew', 'Miller', '2023-8491', '1', 'Non-Binary', 'BSEnvEng'),
	('William Matthew', 'Jones', '2021-4201', '4', 'Non-Binary', 'BSIS'),
	('Alexander David', 'Miller', '2020-5404', '5', 'Male', 'BSEnvEng'),
	('Michael Amelia', 'Garcia', '2024-6831', '3', 'Female', 'BSEE'),
	('John Joseph', 'Digger', '2024-9981', '5', 'Female', 'BSPhil'),
	('Sophia Christopher', 'Davis', '2021-3019', '3', 'Female', 'BSHM'),
	('Ava Joseph', 'Brown', '2023-6523', '2', 'Non-Binary', 'BAPsych'),
	('Alexander Daniel', 'Johnson', '2020-9728', '5', 'Non-Binary', 'BTLEd'),
	('James Mia', 'Johnson', '2024-1940', '3', 'Female', 'BSPhys'),
	('James Mia', 'Smith', '2023-7146', '3', 'Female', 'BSPhys'),
	('John Mia', 'Garcia', '2020-0740', '4', 'Female', 'BSPhys'),
	('Olivia Charlotte', 'Johnson', '2020-9482', '5', 'Female', 'BSIS');